### ISSUE TITLE
DataLoader Error

### ISSUE THREAD

**Issue by Juanfma12** [lcosmo/DGM_pytorch#4]
Hey, so i'm gonna use the Differentiable Graph Module in a project and i cant get it to work with the default settings. When i run the train.py, i get an error (after some epochs run succesfully) stating the following: 

ValueError: An invalid dataloader was passed to `Trainer.test(dataloaders=...)`. Either pass the dataloader to the `.test()` method OR implement `def test_dataloader(self):` in your LightningModule/LightningDataModule.

However, i didn't change anything in the train.py, left it as is. Im using windows 11 (No keops) and using the latest versions of pytorch, pytorch-lightning, sparse and scatter, since i was having errors regarding cuda and methods that were deprecated with the versions in the current readme (pytorch 1.8.1, cuda 10.1, scatter 2.0.8, sparse 0.6.12).

**Comment by With-the-sun** [comment]
hi, Maybe windows just doesn't work(Maybe the author is using linux ) @Juanfma12

**Comment by ZeinabRahbar** [comment]
Traceback (most recent call last):
  File "/content/DGM_pytorch/train.py", line 13, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "/usr/local/lib/python3.10/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 60, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "/usr/local/lib/python3.10/site-packages/torchmetrics/functional/text/bert.py", line 247, in <module>
    def _get_progress_bar(dataloader: DataLoader, verbose: bool = False) -> Union[DataLoader, tqdm.auto.tqdm]:
AttributeError: module 'tqdm' has no attribute 'auto'

**Comment by ZeinabRahbar** [comment]
you can see version that i ran on colab if you need help message me @Juanfma12
